# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Durden
description: Desktop Enviroment for Arcan
category_dir: /
url: http://durden.arcan-fe.com
repository: https://github.com/letoram/durden
markdown: kramdown
sass:
  style: compressed
theme_mode: dark # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Bjorn Stahl
email: contact@arcan-fe.com

navigation:
  - text: Home #ok
    url: /
  - text: Setup #ok
    url: /setup
  - text: Default Bindings #ok
    url: /defbind
  - text: The Menu™ #ok
    url: /menu
  - text: Input #ok
    url: /input
  - text: Display Management #ok
    url: /display
  - text: Visual Enhancements #missing
    url: /visual
  - text: Clipboard #ok
    url: /clipboard
  - text: Statusbar #ok
    url: /statusbar
  - text: Workspaces and Windows # ok
    url: /workspace
  - text: Workspace/Tile
    url: /tiling #ok
  - text: Workspace/Float
    url: /float
  - text: Workspace/Autolayout # ok
    url: /autolay
  - text: IPC # ok
    url: /ipc
  - text: Widgets #missing SS and text
    url: /widgets
  - text: Lockscreen # missing SS and text
    url: /lockscreen
  - text: Record/Stream/Share # missing SS and text
    url: /recstr
  - text: Security/Safety # missing text
    url: /security
  - text: Timers
    url: /timers # missing text
  - text: Core Options
    url: coreopt # missing text
  - text: Audio
    url: audio # missing text
  - text: Launch Targets
    url: /targets # missing text
  - text: Media Browser
    url: /browser # missing SS and text
  - text: Terminal
    url: /terminal # missing text
  - text: Tools
    url: /tools # missing text
  - text: LED Controllers
    url: /led # missing text

projects:
#    description: O
#    link: https://github.com/

social:
  - service: github
    username: letoram
    link: https://github.com/letoram
  - service: twitter
    username: arcan_fe
    link: https://twitter.com/arcan_fe

# Plugins
gems:
  - jekyll-seo-tag
